name: Spring Boot CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (without tests)
        run: ./gradlew build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: lsheon0927/runapp:latest

  # 운영 환경 배포 (main 브랜치)
  deploy-prod:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          script: |
            # 프로젝트 디렉토리로 이동
            mkdir -p ~/running-app
            cd ~/running-app

            # Docker Hub 로그인
            echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

            # docker-compose-prod.yml 파일 생성
            cat > docker-compose-prod.yml << 'EOL'
            version: '3'
            services:
              app:
                image: lsheon0927/runapp:latest
                ports:
                  - "9000:8080"
                depends_on:
                  - postgres
                environment:
                  - SPRING_PROFILES_ACTIVE=prod
                  - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
                  - SPRING_DATASOURCE_USERNAME=${DB_USER}
                  - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
                restart: always
                volumes:
                  - ./logs:/app/logs

              postgres:
                image: postgres:14
                ports:
                  - "5433:5432"
                environment:
                  - POSTGRES_DB=${DB_NAME}
                  - POSTGRES_USER=${DB_USER}
                  - POSTGRES_PASSWORD=${DB_PASSWORD}
                volumes:
                  - postgres-prod-data:/var/lib/postgresql/data
                restart: always

            volumes:
              postgres-prod-data:
            EOL

            # .env.prod 파일 생성
            cat > .env.prod << EOL
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            APP_PORT=9000
            SPRING_PROFILES_ACTIVE=prod
            EOL

            # Docker Compose 실행 (운영 환경 설정)
            docker-compose -f docker-compose-prod.yml --env-file .env.prod down
            docker-compose -f docker-compose-prod.yml --env-file .env.prod pull
            docker-compose -f docker-compose-prod.yml --env-file .env.prod up -d

            # 사용하지 않는 이미지 정리
            docker image prune -f